---
 - name: Installing and lauching filebeat
   hosts: webservers
   become: true
   tasks:

   - name: download filebeat deb
     command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/$

   #- name: install filebeat deb
    # command: dpkg -i filebeat-7.6.1-amd64.deb

   - name: Copy Config file
     copy:
       src: /etc/ansible/files/filebeat-config.yml
       dest: /etc/filebeat/filebeat.yml

   - name: Enable and configure system module
     command: filebeat modules enable system

   - name: Filebeat setup
     command: filebeat setup
 
   - name: Start Filebeat
     command: service filebeat start
